import {getChatGPTUser} from '../../chatgpt-auth';
import {env} from 'cloudflare:workers';
const kinds=['customer','voucher','device','sale','settings'];
const phone=(v:unknown)=>{const p=String(v||'').replace(/[\s()-]/g,'');if(!/^\+?\d{9,15}$/.test(p))throw Error('Enter a valid phone number');return p};
const positive=(v:unknown,max=1000000)=>{const n=Number(v);if(!Number.isFinite(n)||n<=0||n>max)throw Error('Enter a valid positive number');return n};
const name=(v:unknown)=>{const s=String(v||'').trim();if(!s||s.length>150)throw Error('Enter a name (maximum 150 characters)');return s};
async function audit(db:any,owner:string,action:string,target:string){return db.prepare('INSERT INTO records(id,owner,kind,data,created) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),owner,'audit',JSON.stringify({action,target}),new Date().toISOString())}
export async function GET(){const u=await getChatGPTUser();if(!u)return Response.json({error:'Sign in required'},{status:401});const db=env.DB;if(!db)return Response.json({error:'Database unavailable'},{status:503});const {results}=await db.prepare('SELECT * FROM records WHERE owner=? ORDER BY created ASC').bind(u.userId).all<any>();const sms=await db.prepare('SELECT * FROM sms_dispatches WHERE owner=?').bind(u.userId).all<any>();const lookup=new Map(sms.results.map(s=>[s.voucher_id,s]));return Response.json(results.map(r=>{const d=JSON.parse(r.data);if(r.kind==='voucher'&&d.status==='Active'&&d.expires&&d.expires<new Date().toISOString())d.status='Expired';const sent=lookup.get(r.id);return {...d,id:r.id,kind:r.kind,created:r.created,smsStatus:sent?(sent.status==='Sending'&&sent.last_attempt<new Date(Date.now()-120000).toISOString()?'Unconfirmed':sent.status):undefined,smsAttempt:sent?.last_attempt}}),{headers:{'Cache-Control':'no-store'}});}
export async function POST(req:Request){const u=await getChatGPTUser();if(!u)return Response.json({error:'Sign in required'},{status:401});if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid origin'},{status:403});try{const b=await req.json() as Record<string,any>;if(JSON.stringify(b).length>10000)throw Error('Record too large');const db=env.DB;if(!db)throw Error('Database unavailable');const owner=u.userId,now=new Date().toISOString();
if(b.action==='redeem'||b.action==='cancel'){const prior=await db.prepare('SELECT * FROM records WHERE id=? AND owner=? AND kind=?').bind(b.id,owner,'voucher').first<any>();if(!prior)throw Error('Voucher not found');const old=JSON.parse(prior.data);if(old.status!=='Active')throw Error('This voucher is no longer active');if(old.expires&&old.expires<=now)throw Error('This voucher has expired');const receipt=crypto.randomUUID(),redeem=b.action==='redeem';if(redeem&&!b.confirmed)throw Error('Confirm oil has physically been dispensed');const amount=redeem?Number(b.amount):0;if(!Number.isFinite(amount)||amount<0||amount>1000000)throw Error('Enter a valid amount paid');const data={...old,status:redeem?'Redeemed':'Cancelled',completedAt:now,receipt};const change=db.prepare("UPDATE records SET data=? WHERE id=? AND owner=? AND kind='voucher' AND json_extract(data,'$.status')='Active' AND (json_extract(data,'$.expires') IS NULL OR json_extract(data,'$.expires')>?)").bind(JSON.stringify(data),b.id,owner,now);const statements=[change];if(redeem){statements.push(db.prepare("INSERT INTO records(id,owner,kind,data,created) SELECT ?,owner,'sale',?,? FROM records WHERE id=? AND owner=? AND json_extract(data,'$.receipt')=?").bind('redemption:'+b.id,JSON.stringify({litres:old.litres,amount,payment:'Voucher',voucherCode:old.code,customerId:old.customerId,phone:old.phone,source:'Manual redemption',receipt}),now,b.id,owner,receipt));}statements.push(db.prepare("INSERT INTO records(id,owner,kind,data,created) SELECT ?,owner,'audit',?,? FROM records WHERE id=? AND owner=? AND json_extract(data,'$.receipt')=?").bind(crypto.randomUUID(),JSON.stringify({action:redeem?'Voucher redeemed':'Voucher cancelled',target:old.code}),now,b.id,owner,receipt));const result=await db.batch(statements);if(!result[0].meta.changes)throw Error('Voucher changed. Refresh and try again.');return Response.json({ok:true,message:redeem?'Voucher redeemed and sale recorded':'Voucher cancelled'});}
if(!kinds.includes(b.kind))throw Error('Invalid record');let d:Record<string,any>={};if(b.kind==='customer'){d={name:name(b.name),phone:phone(b.phone)};}if(b.kind==='device'){d={name:name(b.name),location:name(b.location)};}if(b.kind==='settings'){d={name:name(b.name),price:positive(b.price)};}if(b.kind==='sale'){if(b.payment!=='Cash')throw Error('Redeem a voucher from the Vouchers page to record voucher sales');d={litres:positive(b.litres,1000),amount:positive(b.amount),payment:'Cash',source:'Manual cash sale'};}
if(b.kind==='voucher'){const customer=await db.prepare("SELECT * FROM records WHERE id=? AND owner=? AND kind='customer'").bind(b.customerId||'',owner).first<any>();if(!customer)throw Error('Select a registered customer');const c=JSON.parse(customer.data);if(!b.expires)throw Error('Choose an expiry date');const expires=new Date(b.expires+'T23:59:59.999Z').toISOString();if(expires<=now)throw Error('Expiry must be today or later');d={customerId:customer.id,customerName:c.name,phone:c.phone,litres:positive(b.litres,1000),value:positive(b.value),expires,status:'Active'};if(b.id)throw Error('Issued vouchers cannot be edited');}
let id=b.id||crypto.randomUUID();if(b.kind==='settings'){const existing=await db.prepare("SELECT id FROM records WHERE owner=? AND kind='settings' LIMIT 1").bind(owner).first<any>();if(existing)id=existing.id;}
if(b.id||b.kind==='settings'){const prior=await db.prepare('SELECT * FROM records WHERE id=? AND owner=? AND kind=?').bind(id,owner,b.kind).first<any>();if(prior){if(!['customer','device','settings'].includes(b.kind))throw Error('This record cannot be edited');await db.batch([db.prepare('UPDATE records SET data=? WHERE id=? AND owner=?').bind(JSON.stringify(d),id,owner),await audit(db,owner,'Updated '+b.kind,String(d.name))]);return Response.json({ok:true,message:'Changes saved'});}if(b.id)throw Error('Record not found');}
if(b.kind==='voucher'){for(let i=0;i<20;i++){d.code=String(100000+crypto.getRandomValues(new Uint32Array(1))[0]%900000);const exists=await db.prepare("SELECT id FROM records WHERE owner=? AND kind='voucher' AND json_extract(data,'$.code')=?").bind(owner,d.code).first();if(exists)continue;try{await db.batch([db.prepare('INSERT INTO voucher_codes(owner,code,voucher_id) VALUES(?,?,?)').bind(owner,d.code,id),db.prepare('INSERT INTO records(id,owner,kind,data,created) VALUES(?,?,?,?,?)').bind(id,owner,b.kind,JSON.stringify(d),now),await audit(db,owner,'Created voucher',d.code)]);return Response.json({ok:true,message:'Voucher created'});}catch(e){if(String(e).includes('UNIQUE'))continue;throw e;}}throw Error('Unable to allocate code. Try again.');}
await db.batch([db.prepare('INSERT INTO records(id,owner,kind,data,created) VALUES(?,?,?,?,?)').bind(id,owner,b.kind,JSON.stringify(d),now),await audit(db,owner,'Created '+b.kind,String(d.name||d.litres+' L'))]);return Response.json({ok:true,message:'Record saved'});
}catch(e){return Response.json({error:e instanceof Error?e.message:'Unable to save'},{status:400});}}
